# Activate these with `source path/to/catmaid_publish/credentials/example.env`

# If your instance requires login to browse
api_token = "ijhwq983vuio2193hwwub1"

# If your instance uses HTTP Basic authentication to access
http_user = "myuser"
http_password = "mypassword"
